import { Cheek } from "../libs/emoticon/Parts.js";

export default {
  id:"cheek",
  label:"ほお",
  items:[
    Cheek("なし"),
    Cheek("スペース", " "),
    Cheek("スペース", "　"),
    Cheek("ほお1", "#"),
    Cheek("ほお1", "◎"),
    Cheek("ほお1", "○"),
    Cheek("ほお1", "〇"),
    Cheek("ほお1", "◍"),
    Cheek("ほお1", "•̤"),
    Cheek("ほお1", "◌"),
    Cheek("ほお1", "⸗"),
    Cheek("ほお1", "⸝⸝"),
    Cheek("ほお1", "⸝"),
    Cheek("ほお1", "…"),
    Cheek("ほお1", "･･"),
    Cheek("ほお1", "･･･"),
    Cheek("ほお1", "∴"),
    Cheek("ほお1", "∵"),
    Cheek("ほお1", "๑"),
    Cheek("ほお1", "∅"),
    Cheek("ほお1", "="),
    Cheek("ほお1", "三"),
    Cheek("ほお1", "═"),
    Cheek("ほお1", "*"),
    Cheek("ほお1", "＊"),
    Cheek("ほお1", "+"),
    Cheek("ほお1", "＋"),
    Cheek("ほお1", "†"),
    Cheek("ほお1", "‡"),
    Cheek("ほお1", "O"),
    Cheek("ほお1", "｡"),
    Cheek("ほお1", "。"),
    Cheek("ほお1", "."),
    Cheek("ほお1", ".."),
    Cheek("ほお1", "..."),
    Cheek("ほお1", "​̤ "),
    Cheek("ほお1", "灬"),
    Cheek("ほお1", "⺌"),
    Cheek("ほお1", ..."⊱⊰"),
    Cheek("ほお1", ..."≫≪"),
    Cheek("ほお1", ..."><"),
    Cheek("ほお1", ..."＞＜"),
    Cheek("ほお1", ..."⚞⚟"),
    Cheek("ほお1", " )", "( "),
    Cheek("ほお1", " ）", "（ "),
    Cheek("ほお1", "▒"),
    Cheek("ほお1", "▓"),
  ],
};